# Generated by Django 5.2.1 on 2025-06-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="image",
            field=models.ImageField(upload_to="servers/"),
        ),
    ]
