# Generated by Django 5.2.1 on 2025-06-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.CharField(max_length=1024),
        ),
    ]
