# Generated by Django 5.2.1 on 2025-06-04 12:26

import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_alter_server_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="image",
            field=models.FileField(
                storage=django_minio_backend.models.MinioBackend(
                    bucket_name="mybucket"
                ),
                upload_to="",
                verbose_name="Object Upload",
            ),
        ),
    ]
